throw new Error('from error module');
console.log('inside error module');
